config/routes.rb
Rails.application.routes.draw do
  resources :sample_pics
  resources :samples
  resources :draft_pics
  resources :drafts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "home#index"

end

app/models/draft_pic.rb
class DraftPic < ApplicationRecord
end

app/controllers/draft_pics_controller.rb
class DraftPicsController < ApplicationController
  before_action :set_draft_pic, only: [:show, :edit, :update, :destroy]

  # GET /draft_pics
  # GET /draft_pics.json
  def index
    @draft_pics = DraftPic.all
  end

  # GET /draft_pics/1
  # GET /draft_pics/1.json
  def show
  end

  # GET /draft_pics/new
  def new
    @draft_pic = DraftPic.new
  end

  # GET /draft_pics/1/edit
  def edit
  end

  # POST /draft_pics
  # POST /draft_pics.json
  def create
    @draft_pic = DraftPic.new(draft_pic_params)

    respond_to do |format|
      if @draft_pic.save
        format.html { redirect_to @draft_pic, notice: 'Draft pic was successfully created.' }
        format.json { render :show, status: :created, location: @draft_pic }
      else
        format.html { render :new }
        format.json { render json: @draft_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /draft_pics/1
  # PATCH/PUT /draft_pics/1.json
  def update
    respond_to do |format|
      if @draft_pic.update(draft_pic_params)
        format.html { redirect_to @draft_pic, notice: 'Draft pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft_pic }
      else
        format.html { render :edit }
        format.json { render json: @draft_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /draft_pics/1
  # DELETE /draft_pics/1.json
  def destroy
    @draft_pic.destroy
    respond_to do |format|
      format.html { redirect_to draft_pics_url, notice: 'Draft pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_draft_pic
      @draft_pic = DraftPic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def draft_pic_params
      params.require(:draft_pic).permit(:pic_file)
    end
end

app/helpers/draft_pics_helper.rb
module DraftPicsHelper
end

app/views/draft_pics/_form.html.erb
<%= form_with(model: draft_pic, local: true) do |form| %>
  <% if draft_pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(draft_pic.errors.count, "error") %> prohibited this draft_pic from being saved:</h2>

      <ul>
      <% draft_pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pic_file %>
    <%= form.text_field :pic_file, id: :draft_pic_pic_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/draft_pics/edit.html.erb
<h1>Editing Draft Pic</h1>

<%= render 'form', draft_pic: @draft_pic %>

<%= link_to 'Show', @draft_pic %> |
<%= link_to 'Back', draft_pics_path %>

app/views/draft_pics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Draft Pics</h1>

<table>
  <thead>
    <tr>
      <th>Pic file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @draft_pics.each do |draft_pic| %>
      <tr>
        <td><%= draft_pic.pic_file %></td>
        <td><%= link_to 'Show', draft_pic %></td>
        <td><%= link_to 'Edit', edit_draft_pic_path(draft_pic) %></td>
        <td><%= link_to 'Destroy', draft_pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Draft Pic', new_draft_pic_path %>

app/views/draft_pics/new.html.erb
<h1>New Draft Pic</h1>

<%= render 'form', draft_pic: @draft_pic %>

<%= link_to 'Back', draft_pics_path %>

app/views/draft_pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pic file:</strong>
  <%= @draft_pic.pic_file %>
</p>

<%= link_to 'Edit', edit_draft_pic_path(@draft_pic) %> |
<%= link_to 'Back', draft_pics_path %>