config/routes.rb
Rails.application.routes.draw do
  resources :sample_pics
  resources :samples
  resources :draft_pics
  resources :drafts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "home#index"

end

app/models/sample_pic.rb
class SamplePic < ApplicationRecord
    belongs_to :sample
end

app/controllers/sample_pics_controller.rb
class SamplePicsController < ApplicationController
  before_action :set_sample_pic, only: [:show, :edit, :update, :destroy]

  # GET /sample_pics
  # GET /sample_pics.json
  def index
    @sample_pics = SamplePic.all
  end

  # GET /sample_pics/1
  # GET /sample_pics/1.json
  def show
  end

  # GET /sample_pics/new
  def new
    @sample_pic = SamplePic.new
  end

  # GET /sample_pics/1/edit
  def edit
  end

  # POST /sample_pics
  # POST /sample_pics.json
  def create
    @sample_pic = SamplePic.new(sample_pic_params)

    respond_to do |format|
      if @sample_pic.save
        format.html { redirect_to @sample_pic, notice: 'Sample pic was successfully created.' }
        format.json { render :show, status: :created, location: @sample_pic }
      else
        format.html { render :new }
        format.json { render json: @sample_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sample_pics/1
  # PATCH/PUT /sample_pics/1.json
  def update
    respond_to do |format|
      if @sample_pic.update(sample_pic_params)
        format.html { redirect_to @sample_pic, notice: 'Sample pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample_pic }
      else
        format.html { render :edit }
        format.json { render json: @sample_pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_pics/1
  # DELETE /sample_pics/1.json
  def destroy
    @sample_pic.destroy
    respond_to do |format|
      format.html { redirect_to sample_pics_url, notice: 'Sample pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample_pic
      @sample_pic = SamplePic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_pic_params
      params.require(:sample_pic).permit(:pic_file)
    end
end

app/helpers/sample_pics_helper.rb
module SamplePicsHelper
end

app/views/sample_pics/_form.html.erb
<%= form_with(model: sample_pic, local: true) do |form| %>
  <% if sample_pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample_pic.errors.count, "error") %> prohibited this sample_pic from being saved:</h2>

      <ul>
      <% sample_pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pic_file %>
    <%= form.text_field :pic_file, id: :sample_pic_pic_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sample_pics/edit.html.erb
<h1>Editing Sample Pic</h1>

<%= render 'form', sample_pic: @sample_pic %>

<%= link_to 'Show', @sample_pic %> |
<%= link_to 'Back', sample_pics_path %>

app/views/sample_pics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sample Pics</h1>

<table>
  <thead>
    <tr>
      <th>Pic file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sample_pics.each do |sample_pic| %>
      <tr>
        <td><%= sample_pic.pic_file %></td>
        <td><%= link_to 'Show', sample_pic %></td>
        <td><%= link_to 'Edit', edit_sample_pic_path(sample_pic) %></td>
        <td><%= link_to 'Destroy', sample_pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample Pic', new_sample_pic_path %>

app/views/sample_pics/new.html.erb
<h1>New Sample Pic</h1>

<%= render 'form', sample_pic: @sample_pic %>

<%= link_to 'Back', sample_pics_path %>

app/views/sample_pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pic file:</strong>
  <%= @sample_pic.pic_file %>
</p>

<%= link_to 'Edit', edit_sample_pic_path(@sample_pic) %> |
<%= link_to 'Back', sample_pics_path %>