config/routes.rb
Rails.application.routes.draw do
  resources :sample_pics
  resources :samples
  resources :draft_pics
  resources :drafts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "home#index"

end

app/models/draft.rb
class Draft < ApplicationRecord
      belongs _to :user
      validates :user_id, presence: true
      #データを引き出す際の順序付け
      default_scope -> { order('created_at DESC') }
      
      has_many :draft_pics
      accepts_nested_attributes_for :draft_pics
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: [:show, :edit, :update, :destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @drafts = Draft.all
  end

  # GET /drafts/1
  # GET /drafts/1.json
  def show
  end

  # GET /drafts/new
  def new
    @draft = Draft.new
  end

  # GET /drafts/1/edit
  def edit
  end

  # POST /drafts
  # POST /drafts.json
  def create
    @draft = Draft.new(draft_params)

    respond_to do |format|
      if @draft.save
        format.html { redirect_to @draft, notice: 'Draft was successfully created.' }
        format.json { render :show, status: :created, location: @draft }
      else
        format.html { render :new }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drafts/1
  # PATCH/PUT /drafts/1.json
  def update
    respond_to do |format|
      if @draft.update(draft_params)
        format.html { redirect_to @draft, notice: 'Draft was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft }
      else
        format.html { render :edit }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafts/1
  # DELETE /drafts/1.json
  def destroy
    @draft.destroy
    respond_to do |format|
      format.html { redirect_to drafts_url, notice: 'Draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_draft
      @draft = Draft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def draft_params
      params.require(:draft).permit(:name, :gender, :expected_price, :explanation, :category, :bookmark)
    end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/_form.html.erb
<%= form_with(model: draft, local: true) do |form| %>
  <% if draft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(draft.errors.count, "error") %> prohibited this draft from being saved:</h2>

      <ul>
      <% draft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :draft_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender, id: :draft_gender %>
  </div>

  <div class="field">
    <%= form.label :expected_price %>
    <%= form.number_field :expected_price, id: :draft_expected_price %>
  </div>

  <div class="field">
    <%= form.label :explanation %>
    <%= form.text_field :explanation, id: :draft_explanation %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.number_field :category, id: :draft_category %>
  </div>

  <div class="field">
    <%= form.label :bookmark %>
    <%= form.number_field :bookmark, id: :draft_bookmark %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drafts/edit.html.erb
<h1>Editing Draft</h1>

<%= render 'form', draft: @draft %>

<%= link_to 'Show', @draft %> |
<%= link_to 'Back', drafts_path %>

app/views/drafts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drafts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Expected price</th>
      <th>Explanation</th>
      <th>Category</th>
      <th>Bookmark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drafts.each do |draft| %>
      <tr>
        <td><%= draft.name %></td>
        <td><%= draft.gender %></td>
        <td><%= draft.expected_price %></td>
        <td><%= draft.explanation %></td>
        <td><%= draft.category %></td>
        <td><%= draft.bookmark %></td>
        <td><%= link_to 'Show', draft %></td>
        <td><%= link_to 'Edit', edit_draft_path(draft) %></td>
        <td><%= link_to 'Destroy', draft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Draft', new_draft_path %>

app/views/drafts/new.html.erb
<h1>New Draft</h1>

<%= render 'form', draft: @draft %>

<%= link_to 'Back', drafts_path %>

app/views/drafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @draft.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @draft.gender %>
</p>

<p>
  <strong>Expected price:</strong>
  <%= @draft.expected_price %>
</p>

<p>
  <strong>Explanation:</strong>
  <%= @draft.explanation %>
</p>

<p>
  <strong>Category:</strong>
  <%= @draft.category %>
</p>

<p>
  <strong>Bookmark:</strong>
  <%= @draft.bookmark %>
</p>

<%= link_to 'Edit', edit_draft_path(@draft) %> |
<%= link_to 'Back', drafts_path %>